import React, { useState, useEffect } from 'react';
import { jsPDF } from 'jspdf';
import { historyService } from '../services/api';
import { Copy, FileText, Download, Share2, RefreshCw, Check, SkipForward, ShieldAlert, CheckCircle, AlertTriangle, Trash2 } from 'lucide-react';

const parseScores = (text) => {
  if (!text) return { routeScore: 80, vehicleScore: 85, riskFactor: 'Moderate Risk', cleanedText: '' };
  
  const routeMatch = text.match(/\[ROUTE_SAFETY_SCORE\]:\s*(\d+)%/i);
  const vehicleMatch = text.match(/\[VEHICLE_SUITABILITY_SCORE\]:\s*(\d+)%/i);
  const riskMatch = text.match(/\[OVERALL_RISK_FACTOR\]:\s*([a-zA-Z\s\-_]+)/i);

  const routeScore = routeMatch ? parseInt(routeMatch[1], 10) : 80;
  const vehicleScore = vehicleMatch ? parseInt(vehicleMatch[1], 10) : 85;
  const riskFactor = (riskMatch ? riskMatch[1].trim() : 'Moderate Risk')
    .replace(/[^a-zA-Z\s]/g, '')
    .trim();

  // Clean the response text by removing the raw scores block
  let cleanedText = text
    .replace(/\[ROUTE_SAFETY_SCORE\]:\s*\d+%/gi, '')
    .replace(/\[VEHICLE_SUITABILITY_SCORE\]:\s*\d+%/gi, '')
    .replace(/\[OVERALL_RISK_FACTOR\]:\s*[a-zA-Z\s\-_]+/gi, '')
    .replace(/Overall Safety Scores/gi, '')
    .replace(/\[\s*\]/g, '')
    .trim();

  return { routeScore, vehicleScore, riskFactor, cleanedText };
};

const OutputCard = ({ generation, onRegenerate, loadingRegen, onDelete }) => {
  const [copied, setCopied] = useState(false);
  const [typedText, setTypedText] = useState('');
  const [typingComplete, setTypingComplete] = useState(false);
  const [skipTyping, setSkipTyping] = useState(false);

  const { routeScore, vehicleScore, riskFactor, cleanedText } = parseScores(generation?.aiResponse);

  // typing animation effect
  useEffect(() => {
    if (!cleanedText) return;
    
    if (skipTyping) {
      setTypedText(cleanedText);
      setTypingComplete(true);
      return;
    }

    setTypingComplete(false);
    setTypedText('');
    let index = 0;
    const fullText = cleanedText;
    const chunkSize = 25; // number of characters per frame for speed
    
    const interval = setInterval(() => {
      if (index < fullText.length) {
        setTypedText(fullText.slice(0, index + chunkSize));
        index += chunkSize;
      } else {
        setTypedText(fullText);
        setTypingComplete(true);
        clearInterval(interval);
      }
    }, 20);

    return () => clearInterval(interval);
  }, [cleanedText, skipTyping]);

  if (!generation) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(cleanedText);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadTXT = () => {
    const element = document.createElement('a');
    const file = new Blob([
      `MANIVTHA TOURS & TRAVELS - SAFETY BRIEFING\n`,
      `====================================================\n`,
      `Origin: ${generation.routeFrom}\n`,
      `Destination: ${generation.routeTo}\n`,
      `Season: ${generation.season}\n`,
      `Vehicle Type: ${generation.vehicleType}\n`,
      `Duration: ${generation.duration}\n`,
      `Generated By: ${generation.adminName}\n`,
      `Timestamp: ${new Date(generation.createdAt).toLocaleString()}\n`,
      `Model Engine: ${generation.selectedModel}\n`,
      `====================================================\n`,
      `SAFETY RATINGS:\n`,
      `- Route Safety Index: ${routeScore}%\n`,
      `- Vehicle Suitability: ${vehicleScore}%\n`,
      `- Overall Risk Factor: ${riskFactor.toUpperCase()}\n`,
      `====================================================\n\n`,
      cleanedText
    ], { type: 'text/plain;charset=utf-8' });
    element.href = URL.createObjectURL(file);
    element.download = `Briefing_${generation.routeFrom}_to_${generation.routeTo}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const downloadPDF = () => {
    const doc = new jsPDF();
    
    // Page Header
    doc.setFillColor(30, 41, 59); // dark navy bar
    doc.rect(0, 0, 210, 35, 'F');
    
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(16);
    doc.setTextColor(255, 255, 255);
    doc.text("MANIVTHA TOURS & TRAVELS", 20, 15);
    
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(10);
    doc.text("AI Outstation Safety Briefing & Risk Protocol", 20, 24);
    
    // Sub headers
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(10);
    doc.setTextColor(30, 41, 59);
    doc.text("TRIP PARAMETERS:", 20, 45);
    
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(9);
    doc.text(`Origin Route: ${generation.routeFrom} to ${generation.routeTo}`, 20, 52);
    doc.text(`Vehicle: ${generation.vehicleType} | Season: ${generation.season}`, 20, 57);
    doc.text(`Duration: ${generation.duration} | Model: ${generation.selectedModel}`, 20, 62);
    doc.text(`Dispatched By: ${generation.adminName} | Date: ${new Date(generation.createdAt).toLocaleString()}`, 20, 67);
    
    // Safety scores in PDF
    doc.setFont("Helvetica", "bold");
    doc.text("SAFETY INDEX EVALUATION:", 115, 45);
    doc.setFont("Helvetica", "normal");
    doc.text(`Route Safety Score: ${routeScore}%`, 115, 52);
    doc.text(`Vehicle Suitability: ${vehicleScore}%`, 115, 57);
    doc.text(`Overall Risk Rating: ${riskFactor.toUpperCase()}`, 115, 62);

    doc.line(20, 72, 190, 72);
    
    // Content body
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(40, 40, 40);
    
    const splitText = doc.splitTextToSize(cleanedText, 170);
    let y = 80;
    
    for (let i = 0; i < splitText.length; i++) {
      if (y > 275) {
        doc.addPage();
        y = 20;
      }
      doc.text(splitText[i], 20, y);
      y += 6;
    }
    
    doc.save(`SafetyBriefing_${generation.routeFrom}_to_${generation.routeTo}.pdf`);
  };

  const handleShare = async () => {
    const shareText = `Manivtha Safety Briefing: ${generation.routeFrom} to ${generation.routeTo}. Route Safety: ${routeScore}%, Vehicle Suitability: ${vehicleScore}%, Risk: ${riskFactor.toUpperCase()}`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'Trip Safety Briefing',
          text: shareText,
          url: window.location.origin
        });
      } catch (err) {
        console.log('Error sharing:', err);
      }
    } else {
      navigator.clipboard.writeText(shareText);
      alert('Share description copied to clipboard!');
    }
  };

  const handleDelete = async () => {
    if (!window.confirm('Are you sure you want to permanently delete this trip safety briefing?')) {
      return;
    }
    
    try {
      await historyService.deleteHistoryById(generation.id);
      if (onDelete) {
        onDelete(generation.id);
      } else {
        alert('Briefing deleted successfully.');
        window.location.reload();
      }
    } catch (err) {
      console.error('Failed to delete briefing:', err);
      alert('Error deleting briefing. Please try again.');
    }
  };

  return (
    <div className="glass-panel rounded-2xl shadow-glass-light dark:shadow-glass-dark border border-slate-200 dark:border-slate-800 overflow-hidden">
      {/* Top action header bar */}
      <div className="flex flex-wrap items-center justify-between gap-2 p-4 bg-slate-100/55 dark:bg-slate-900/50 border-b border-slate-200 dark:border-slate-800">
        <div className="flex items-center gap-2">
          <span className="inline-block w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse" />
          <span className="text-xs font-bold text-slate-700 dark:text-slate-300">Briefing Ready ({generation.selectedModel})</span>
          <span className="text-[10px] text-slate-400 font-mono">({generation.responseTimeMs}ms)</span>
        </div>

        <div className="flex items-center gap-1">
          {/* Skip typing animation button */}
          {!typingComplete && (
            <button
              onClick={() => setSkipTyping(true)}
              className="p-1.5 rounded-lg text-slate-500 dark:text-slate-400 hover:bg-slate-200/50 dark:hover:bg-slate-800 flex items-center gap-1 text-[11px] font-semibold transition"
              title="Show entire response"
            >
              <SkipForward className="w-3.5 h-3.5" /> Skip
            </button>
          )}

          {/* Copy */}
          <button
            onClick={handleCopy}
            className="p-1.5 rounded-lg text-slate-600 dark:text-slate-400 hover:bg-slate-200/50 dark:hover:bg-slate-800 transition"
            title="Copy Cleaned Briefing to Clipboard"
          >
            {copied ? <Check className="w-4 h-4 text-green-500" /> : <Copy className="w-4 h-4" />}
          </button>

          {/* TXT */}
          <button
            onClick={downloadTXT}
            className="p-1.5 rounded-lg text-slate-600 dark:text-slate-400 hover:bg-slate-200/50 dark:hover:bg-slate-800 transition"
            title="Download TXT Report"
          >
            <FileText className="w-4 h-4" />
          </button>

          {/* PDF */}
          <button
            onClick={downloadPDF}
            className="p-1.5 rounded-lg text-slate-600 dark:text-slate-400 hover:bg-slate-200/50 dark:hover:bg-slate-800 transition"
            title="Download PDF Safety Document"
          >
            <Download className="w-4 h-4" />
          </button>

          {/* Share */}
          <button
            onClick={handleShare}
            className="p-1.5 rounded-lg text-slate-600 dark:text-slate-400 hover:bg-slate-200/50 dark:hover:bg-slate-800 transition"
            title="Share briefing text"
          >
            <Share2 className="w-4 h-4" />
          </button>

          {/* Delete Briefing */}
          <button
            onClick={handleDelete}
            className="p-1.5 rounded-lg text-slate-600 dark:text-slate-400 hover:text-red-500 hover:bg-red-500/10 transition cursor-pointer"
            title="Delete this Briefing"
          >
            <Trash2 className="w-4 h-4" />
          </button>

          {/* Regenerate */}
          {onRegenerate && (
            <button
              onClick={() => {
                setSkipTyping(false);
                onRegenerate(generation);
              }}
              disabled={loadingRegen}
              className="p-1.5 rounded-lg text-slate-600 dark:text-slate-400 hover:bg-slate-200/50 dark:hover:bg-slate-800 transition disabled:opacity-50"
              title="Regenerate safety report"
            >
              <RefreshCw className={`w-4 h-4 ${loadingRegen ? 'animate-spin' : ''}`} />
            </button>
          )}
        </div>
      </div>

      {/* Visual Safety Indexes / Risk Factors Dashboard */}
      <div className="p-5 bg-slate-50/40 dark:bg-slate-900/20 border-b border-slate-200 dark:border-slate-800 grid grid-cols-1 md:grid-cols-3 gap-4">
        {/* Route Safety Score */}
        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-950 border border-slate-100 dark:border-slate-800/80 shadow-sm flex flex-col justify-between">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-2">Route Safety Index</span>
          <div className="flex items-center gap-3">
            <div className="relative flex items-center justify-center">
              <span className={`text-lg font-extrabold ${routeScore >= 85 ? 'text-green-500' : routeScore >= 70 ? 'text-amber-500' : 'text-red-500'}`}>
                {routeScore}%
              </span>
            </div>
            <div className="flex-1 space-y-1">
              <div className="h-2 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                <div 
                  className={`h-full rounded-full transition-all duration-1000 ${routeScore >= 85 ? 'bg-green-500' : routeScore >= 70 ? 'bg-amber-500' : 'bg-red-500'}`}
                  style={{ width: `${routeScore}%` }}
                />
              </div>
              <span className="text-[10px] text-slate-500">Weather & surface rating</span>
            </div>
          </div>
        </div>

        {/* Vehicle Suitability Score */}
        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-950 border border-slate-100 dark:border-slate-800/80 shadow-sm flex flex-col justify-between">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-2">Vehicle Suitability</span>
          <div className="flex items-center gap-3">
            <div className="relative flex items-center justify-center">
              <span className={`text-lg font-extrabold ${vehicleScore >= 85 ? 'text-green-500' : vehicleScore >= 70 ? 'text-amber-500' : 'text-red-500'}`}>
                {vehicleScore}%
              </span>
            </div>
            <div className="flex-1 space-y-1">
              <div className="h-2 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                <div 
                  className={`h-full rounded-full transition-all duration-1000 ${vehicleScore >= 85 ? 'bg-green-500' : vehicleScore >= 70 ? 'bg-amber-500' : 'bg-red-500'}`}
                  style={{ width: `${vehicleScore}%` }}
                />
              </div>
              <span className="text-[10px] text-slate-500">Model capability for route</span>
            </div>
          </div>
        </div>

        {/* Overall Risk Level */}
        <div className="p-3.5 rounded-xl bg-white dark:bg-slate-950 border border-slate-100 dark:border-slate-800/80 shadow-sm flex flex-col justify-between">
          <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-2">Assessed Risk Factor</span>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-1.5 text-slate-500 dark:text-slate-400">
              {riskFactor.toLowerCase().includes('low') ? (
                <CheckCircle className="w-4 h-4 text-green-500" />
              ) : riskFactor.toLowerCase().includes('moderate') ? (
                <AlertTriangle className="w-4 h-4 text-amber-500" />
              ) : (
                <ShieldAlert className="w-4 h-4 text-red-500" />
              )}
              <span className="text-xs font-semibold">E2E Score:</span>
            </div>
            <span className={`px-2.5 py-1 rounded-lg text-xs font-extrabold border ${
              riskFactor.toLowerCase().includes('low') 
                ? 'bg-green-500/10 border-green-500/20 text-green-600 dark:text-green-400' 
                : riskFactor.toLowerCase().includes('moderate') 
                  ? 'bg-amber-500/10 border-amber-500/20 text-amber-600 dark:text-amber-400' 
                  : 'bg-red-500/10 border-red-500/20 text-red-600 dark:text-red-400'
            }`}>
              {riskFactor.toUpperCase() || 'MODERATE RISK'}
            </span>
          </div>
        </div>
      </div>

      {/* Briefing Text Output */}
      <div className="p-6 max-h-[500px] overflow-y-auto text-sm leading-relaxed font-sans text-slate-700 dark:text-slate-300 bg-white/40 dark:bg-slate-950/20 whitespace-pre-line border-b border-slate-100 dark:border-slate-800/80">
        {typedText}
        {!typingComplete && (
          <span className="inline-block w-1.5 h-4 ml-1 bg-brand-500 typing-caret" />
        )}
      </div>
    </div>
  );
};

export default OutputCard;
